/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var dependencies_gogoproto_gogo_pb = require('../../../../dependencies/gogoproto/gogo_pb.js');
var temporal_api_enums_v1_common_pb = require('../../../../temporal/api/enums/v1/common_pb.js');
goog.exportSymbol('proto.temporal.api.version.v1.Alert', null, global);
goog.exportSymbol('proto.temporal.api.version.v1.ReleaseInfo', null, global);
goog.exportSymbol('proto.temporal.api.version.v1.VersionInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.version.v1.ReleaseInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.version.v1.ReleaseInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.version.v1.ReleaseInfo.displayName = 'proto.temporal.api.version.v1.ReleaseInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.version.v1.ReleaseInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.version.v1.ReleaseInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.version.v1.ReleaseInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.version.v1.ReleaseInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    releaseTime: (f = msg.getReleaseTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    notes: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.version.v1.ReleaseInfo}
 */
proto.temporal.api.version.v1.ReleaseInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.version.v1.ReleaseInfo;
  return proto.temporal.api.version.v1.ReleaseInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.version.v1.ReleaseInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.version.v1.ReleaseInfo}
 */
proto.temporal.api.version.v1.ReleaseInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setReleaseTime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.version.v1.ReleaseInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.version.v1.ReleaseInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.version.v1.ReleaseInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.version.v1.ReleaseInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReleaseTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getNotes();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.temporal.api.version.v1.ReleaseInfo.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.version.v1.ReleaseInfo.prototype.setVersion = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp release_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.version.v1.ReleaseInfo.prototype.getReleaseTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.version.v1.ReleaseInfo.prototype.setReleaseTime = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.temporal.api.version.v1.ReleaseInfo.prototype.clearReleaseTime = function() {
  this.setReleaseTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.version.v1.ReleaseInfo.prototype.hasReleaseTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string notes = 3;
 * @return {string}
 */
proto.temporal.api.version.v1.ReleaseInfo.prototype.getNotes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.temporal.api.version.v1.ReleaseInfo.prototype.setNotes = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.version.v1.Alert = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.version.v1.Alert, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.version.v1.Alert.displayName = 'proto.temporal.api.version.v1.Alert';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.version.v1.Alert.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.version.v1.Alert.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.version.v1.Alert} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.version.v1.Alert.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    severity: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.version.v1.Alert}
 */
proto.temporal.api.version.v1.Alert.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.version.v1.Alert;
  return proto.temporal.api.version.v1.Alert.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.version.v1.Alert} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.version.v1.Alert}
 */
proto.temporal.api.version.v1.Alert.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {!proto.temporal.api.enums.v1.Severity} */ (reader.readEnum());
      msg.setSeverity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.version.v1.Alert.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.version.v1.Alert.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.version.v1.Alert} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.version.v1.Alert.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSeverity();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.temporal.api.version.v1.Alert.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.version.v1.Alert.prototype.setMessage = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional temporal.api.enums.v1.Severity severity = 2;
 * @return {!proto.temporal.api.enums.v1.Severity}
 */
proto.temporal.api.version.v1.Alert.prototype.getSeverity = function() {
  return /** @type {!proto.temporal.api.enums.v1.Severity} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.temporal.api.enums.v1.Severity} value */
proto.temporal.api.version.v1.Alert.prototype.setSeverity = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.version.v1.VersionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.temporal.api.version.v1.VersionInfo.repeatedFields_, null);
};
goog.inherits(proto.temporal.api.version.v1.VersionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.version.v1.VersionInfo.displayName = 'proto.temporal.api.version.v1.VersionInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.temporal.api.version.v1.VersionInfo.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.version.v1.VersionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.version.v1.VersionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.version.v1.VersionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    current: (f = msg.getCurrent()) && proto.temporal.api.version.v1.ReleaseInfo.toObject(includeInstance, f),
    recommended: (f = msg.getRecommended()) && proto.temporal.api.version.v1.ReleaseInfo.toObject(includeInstance, f),
    instructions: jspb.Message.getFieldWithDefault(msg, 3, ""),
    alertsList: jspb.Message.toObjectList(msg.getAlertsList(),
    proto.temporal.api.version.v1.Alert.toObject, includeInstance),
    lastUpdateTime: (f = msg.getLastUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.version.v1.VersionInfo}
 */
proto.temporal.api.version.v1.VersionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.version.v1.VersionInfo;
  return proto.temporal.api.version.v1.VersionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.version.v1.VersionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.version.v1.VersionInfo}
 */
proto.temporal.api.version.v1.VersionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.temporal.api.version.v1.ReleaseInfo;
      reader.readMessage(value,proto.temporal.api.version.v1.ReleaseInfo.deserializeBinaryFromReader);
      msg.setCurrent(value);
      break;
    case 2:
      var value = new proto.temporal.api.version.v1.ReleaseInfo;
      reader.readMessage(value,proto.temporal.api.version.v1.ReleaseInfo.deserializeBinaryFromReader);
      msg.setRecommended(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstructions(value);
      break;
    case 4:
      var value = new proto.temporal.api.version.v1.Alert;
      reader.readMessage(value,proto.temporal.api.version.v1.Alert.deserializeBinaryFromReader);
      msg.addAlerts(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastUpdateTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.version.v1.VersionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.version.v1.VersionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.version.v1.VersionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.temporal.api.version.v1.ReleaseInfo.serializeBinaryToWriter
    );
  }
  f = message.getRecommended();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.temporal.api.version.v1.ReleaseInfo.serializeBinaryToWriter
    );
  }
  f = message.getInstructions();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAlertsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.temporal.api.version.v1.Alert.serializeBinaryToWriter
    );
  }
  f = message.getLastUpdateTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional ReleaseInfo current = 1;
 * @return {?proto.temporal.api.version.v1.ReleaseInfo}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.getCurrent = function() {
  return /** @type{?proto.temporal.api.version.v1.ReleaseInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.version.v1.ReleaseInfo, 1));
};


/** @param {?proto.temporal.api.version.v1.ReleaseInfo|undefined} value */
proto.temporal.api.version.v1.VersionInfo.prototype.setCurrent = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.temporal.api.version.v1.VersionInfo.prototype.clearCurrent = function() {
  this.setCurrent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.hasCurrent = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ReleaseInfo recommended = 2;
 * @return {?proto.temporal.api.version.v1.ReleaseInfo}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.getRecommended = function() {
  return /** @type{?proto.temporal.api.version.v1.ReleaseInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.version.v1.ReleaseInfo, 2));
};


/** @param {?proto.temporal.api.version.v1.ReleaseInfo|undefined} value */
proto.temporal.api.version.v1.VersionInfo.prototype.setRecommended = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.temporal.api.version.v1.VersionInfo.prototype.clearRecommended = function() {
  this.setRecommended(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.hasRecommended = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string instructions = 3;
 * @return {string}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.getInstructions = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.temporal.api.version.v1.VersionInfo.prototype.setInstructions = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated Alert alerts = 4;
 * @return {!Array<!proto.temporal.api.version.v1.Alert>}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.getAlertsList = function() {
  return /** @type{!Array<!proto.temporal.api.version.v1.Alert>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.temporal.api.version.v1.Alert, 4));
};


/** @param {!Array<!proto.temporal.api.version.v1.Alert>} value */
proto.temporal.api.version.v1.VersionInfo.prototype.setAlertsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.temporal.api.version.v1.Alert=} opt_value
 * @param {number=} opt_index
 * @return {!proto.temporal.api.version.v1.Alert}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.addAlerts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.temporal.api.version.v1.Alert, opt_index);
};


proto.temporal.api.version.v1.VersionInfo.prototype.clearAlertsList = function() {
  this.setAlertsList([]);
};


/**
 * optional google.protobuf.Timestamp last_update_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.getLastUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.version.v1.VersionInfo.prototype.setLastUpdateTime = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.temporal.api.version.v1.VersionInfo.prototype.clearLastUpdateTime = function() {
  this.setLastUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.version.v1.VersionInfo.prototype.hasLastUpdateTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.temporal.api.version.v1);
