/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var dependencies_gogoproto_gogo_pb = require('../../../../dependencies/gogoproto/gogo_pb.js');
var temporal_api_enums_v1_workflow_pb = require('../../../../temporal/api/enums/v1/workflow_pb.js');
var temporal_api_common_v1_message_pb = require('../../../../temporal/api/common/v1/message_pb.js');
var temporal_api_failure_v1_message_pb = require('../../../../temporal/api/failure/v1/message_pb.js');
var temporal_api_taskqueue_v1_message_pb = require('../../../../temporal/api/taskqueue/v1/message_pb.js');
goog.exportSymbol('proto.temporal.api.workflow.v1.PendingActivityInfo', null, global);
goog.exportSymbol('proto.temporal.api.workflow.v1.PendingChildExecutionInfo', null, global);
goog.exportSymbol('proto.temporal.api.workflow.v1.ResetPointInfo', null, global);
goog.exportSymbol('proto.temporal.api.workflow.v1.ResetPoints', null, global);
goog.exportSymbol('proto.temporal.api.workflow.v1.WorkflowExecutionConfig', null, global);
goog.exportSymbol('proto.temporal.api.workflow.v1.WorkflowExecutionInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.workflow.v1.WorkflowExecutionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.workflow.v1.WorkflowExecutionInfo.displayName = 'proto.temporal.api.workflow.v1.WorkflowExecutionInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.workflow.v1.WorkflowExecutionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.workflow.v1.WorkflowExecutionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    execution: (f = msg.getExecution()) && temporal_api_common_v1_message_pb.WorkflowExecution.toObject(includeInstance, f),
    type: (f = msg.getType()) && temporal_api_common_v1_message_pb.WorkflowType.toObject(includeInstance, f),
    startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    closeTime: (f = msg.getCloseTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 5, 0),
    historyLength: jspb.Message.getFieldWithDefault(msg, 6, 0),
    parentNamespaceId: jspb.Message.getFieldWithDefault(msg, 7, ""),
    parentExecution: (f = msg.getParentExecution()) && temporal_api_common_v1_message_pb.WorkflowExecution.toObject(includeInstance, f),
    executionTime: (f = msg.getExecutionTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    memo: (f = msg.getMemo()) && temporal_api_common_v1_message_pb.Memo.toObject(includeInstance, f),
    searchAttributes: (f = msg.getSearchAttributes()) && temporal_api_common_v1_message_pb.SearchAttributes.toObject(includeInstance, f),
    autoResetPoints: (f = msg.getAutoResetPoints()) && proto.temporal.api.workflow.v1.ResetPoints.toObject(includeInstance, f),
    taskQueue: jspb.Message.getFieldWithDefault(msg, 13, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.workflow.v1.WorkflowExecutionInfo}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.workflow.v1.WorkflowExecutionInfo;
  return proto.temporal.api.workflow.v1.WorkflowExecutionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.workflow.v1.WorkflowExecutionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.workflow.v1.WorkflowExecutionInfo}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new temporal_api_common_v1_message_pb.WorkflowExecution;
      reader.readMessage(value,temporal_api_common_v1_message_pb.WorkflowExecution.deserializeBinaryFromReader);
      msg.setExecution(value);
      break;
    case 2:
      var value = new temporal_api_common_v1_message_pb.WorkflowType;
      reader.readMessage(value,temporal_api_common_v1_message_pb.WorkflowType.deserializeBinaryFromReader);
      msg.setType(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCloseTime(value);
      break;
    case 5:
      var value = /** @type {!proto.temporal.api.enums.v1.WorkflowExecutionStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHistoryLength(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentNamespaceId(value);
      break;
    case 8:
      var value = new temporal_api_common_v1_message_pb.WorkflowExecution;
      reader.readMessage(value,temporal_api_common_v1_message_pb.WorkflowExecution.deserializeBinaryFromReader);
      msg.setParentExecution(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExecutionTime(value);
      break;
    case 10:
      var value = new temporal_api_common_v1_message_pb.Memo;
      reader.readMessage(value,temporal_api_common_v1_message_pb.Memo.deserializeBinaryFromReader);
      msg.setMemo(value);
      break;
    case 11:
      var value = new temporal_api_common_v1_message_pb.SearchAttributes;
      reader.readMessage(value,temporal_api_common_v1_message_pb.SearchAttributes.deserializeBinaryFromReader);
      msg.setSearchAttributes(value);
      break;
    case 12:
      var value = new proto.temporal.api.workflow.v1.ResetPoints;
      reader.readMessage(value,proto.temporal.api.workflow.v1.ResetPoints.deserializeBinaryFromReader);
      msg.setAutoResetPoints(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaskQueue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.workflow.v1.WorkflowExecutionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.workflow.v1.WorkflowExecutionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExecution();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      temporal_api_common_v1_message_pb.WorkflowExecution.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      temporal_api_common_v1_message_pb.WorkflowType.serializeBinaryToWriter
    );
  }
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCloseTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getHistoryLength();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getParentNamespaceId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getParentExecution();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      temporal_api_common_v1_message_pb.WorkflowExecution.serializeBinaryToWriter
    );
  }
  f = message.getExecutionTime();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMemo();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      temporal_api_common_v1_message_pb.Memo.serializeBinaryToWriter
    );
  }
  f = message.getSearchAttributes();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      temporal_api_common_v1_message_pb.SearchAttributes.serializeBinaryToWriter
    );
  }
  f = message.getAutoResetPoints();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.temporal.api.workflow.v1.ResetPoints.serializeBinaryToWriter
    );
  }
  f = message.getTaskQueue();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
};


/**
 * optional temporal.api.common.v1.WorkflowExecution execution = 1;
 * @return {?proto.temporal.api.common.v1.WorkflowExecution}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getExecution = function() {
  return /** @type{?proto.temporal.api.common.v1.WorkflowExecution} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.WorkflowExecution, 1));
};


/** @param {?proto.temporal.api.common.v1.WorkflowExecution|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setExecution = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearExecution = function() {
  this.setExecution(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasExecution = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional temporal.api.common.v1.WorkflowType type = 2;
 * @return {?proto.temporal.api.common.v1.WorkflowType}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getType = function() {
  return /** @type{?proto.temporal.api.common.v1.WorkflowType} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.WorkflowType, 2));
};


/** @param {?proto.temporal.api.common.v1.WorkflowType|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setType = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearType = function() {
  this.setType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasType = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp start_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setStartTime = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearStartTime = function() {
  this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp close_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getCloseTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setCloseTime = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearCloseTime = function() {
  this.setCloseTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasCloseTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional temporal.api.enums.v1.WorkflowExecutionStatus status = 5;
 * @return {!proto.temporal.api.enums.v1.WorkflowExecutionStatus}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getStatus = function() {
  return /** @type {!proto.temporal.api.enums.v1.WorkflowExecutionStatus} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.temporal.api.enums.v1.WorkflowExecutionStatus} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional int64 history_length = 6;
 * @return {number}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getHistoryLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setHistoryLength = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string parent_namespace_id = 7;
 * @return {string}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getParentNamespaceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setParentNamespaceId = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional temporal.api.common.v1.WorkflowExecution parent_execution = 8;
 * @return {?proto.temporal.api.common.v1.WorkflowExecution}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getParentExecution = function() {
  return /** @type{?proto.temporal.api.common.v1.WorkflowExecution} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.WorkflowExecution, 8));
};


/** @param {?proto.temporal.api.common.v1.WorkflowExecution|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setParentExecution = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearParentExecution = function() {
  this.setParentExecution(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasParentExecution = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp execution_time = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getExecutionTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setExecutionTime = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearExecutionTime = function() {
  this.setExecutionTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasExecutionTime = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional temporal.api.common.v1.Memo memo = 10;
 * @return {?proto.temporal.api.common.v1.Memo}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getMemo = function() {
  return /** @type{?proto.temporal.api.common.v1.Memo} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.Memo, 10));
};


/** @param {?proto.temporal.api.common.v1.Memo|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setMemo = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearMemo = function() {
  this.setMemo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasMemo = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional temporal.api.common.v1.SearchAttributes search_attributes = 11;
 * @return {?proto.temporal.api.common.v1.SearchAttributes}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getSearchAttributes = function() {
  return /** @type{?proto.temporal.api.common.v1.SearchAttributes} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.SearchAttributes, 11));
};


/** @param {?proto.temporal.api.common.v1.SearchAttributes|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setSearchAttributes = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearSearchAttributes = function() {
  this.setSearchAttributes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasSearchAttributes = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ResetPoints auto_reset_points = 12;
 * @return {?proto.temporal.api.workflow.v1.ResetPoints}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getAutoResetPoints = function() {
  return /** @type{?proto.temporal.api.workflow.v1.ResetPoints} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.workflow.v1.ResetPoints, 12));
};


/** @param {?proto.temporal.api.workflow.v1.ResetPoints|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setAutoResetPoints = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.clearAutoResetPoints = function() {
  this.setAutoResetPoints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.hasAutoResetPoints = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string task_queue = 13;
 * @return {string}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.getTaskQueue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.WorkflowExecutionInfo.prototype.setTaskQueue = function(value) {
  jspb.Message.setProto3StringField(this, 13, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.workflow.v1.WorkflowExecutionConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.workflow.v1.WorkflowExecutionConfig.displayName = 'proto.temporal.api.workflow.v1.WorkflowExecutionConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.workflow.v1.WorkflowExecutionConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.workflow.v1.WorkflowExecutionConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskQueue: (f = msg.getTaskQueue()) && temporal_api_taskqueue_v1_message_pb.TaskQueue.toObject(includeInstance, f),
    workflowExecutionTimeout: (f = msg.getWorkflowExecutionTimeout()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    workflowRunTimeout: (f = msg.getWorkflowRunTimeout()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    defaultWorkflowTaskTimeout: (f = msg.getDefaultWorkflowTaskTimeout()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.workflow.v1.WorkflowExecutionConfig}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.workflow.v1.WorkflowExecutionConfig;
  return proto.temporal.api.workflow.v1.WorkflowExecutionConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.workflow.v1.WorkflowExecutionConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.workflow.v1.WorkflowExecutionConfig}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new temporal_api_taskqueue_v1_message_pb.TaskQueue;
      reader.readMessage(value,temporal_api_taskqueue_v1_message_pb.TaskQueue.deserializeBinaryFromReader);
      msg.setTaskQueue(value);
      break;
    case 2:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setWorkflowExecutionTimeout(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setWorkflowRunTimeout(value);
      break;
    case 4:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDefaultWorkflowTaskTimeout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.workflow.v1.WorkflowExecutionConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.workflow.v1.WorkflowExecutionConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTaskQueue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      temporal_api_taskqueue_v1_message_pb.TaskQueue.serializeBinaryToWriter
    );
  }
  f = message.getWorkflowExecutionTimeout();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getWorkflowRunTimeout();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getDefaultWorkflowTaskTimeout();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional temporal.api.taskqueue.v1.TaskQueue task_queue = 1;
 * @return {?proto.temporal.api.taskqueue.v1.TaskQueue}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.getTaskQueue = function() {
  return /** @type{?proto.temporal.api.taskqueue.v1.TaskQueue} */ (
    jspb.Message.getWrapperField(this, temporal_api_taskqueue_v1_message_pb.TaskQueue, 1));
};


/** @param {?proto.temporal.api.taskqueue.v1.TaskQueue|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.setTaskQueue = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.clearTaskQueue = function() {
  this.setTaskQueue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.hasTaskQueue = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Duration workflow_execution_timeout = 2;
 * @return {?proto.google.protobuf.Duration}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.getWorkflowExecutionTimeout = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 2));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.setWorkflowExecutionTimeout = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.clearWorkflowExecutionTimeout = function() {
  this.setWorkflowExecutionTimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.hasWorkflowExecutionTimeout = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Duration workflow_run_timeout = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.getWorkflowRunTimeout = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.setWorkflowRunTimeout = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.clearWorkflowRunTimeout = function() {
  this.setWorkflowRunTimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.hasWorkflowRunTimeout = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Duration default_workflow_task_timeout = 4;
 * @return {?proto.google.protobuf.Duration}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.getDefaultWorkflowTaskTimeout = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 4));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.setDefaultWorkflowTaskTimeout = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.clearDefaultWorkflowTaskTimeout = function() {
  this.setDefaultWorkflowTaskTimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.WorkflowExecutionConfig.prototype.hasDefaultWorkflowTaskTimeout = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.workflow.v1.PendingActivityInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.workflow.v1.PendingActivityInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.workflow.v1.PendingActivityInfo.displayName = 'proto.temporal.api.workflow.v1.PendingActivityInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.workflow.v1.PendingActivityInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.workflow.v1.PendingActivityInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    activityId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    activityType: (f = msg.getActivityType()) && temporal_api_common_v1_message_pb.ActivityType.toObject(includeInstance, f),
    state: jspb.Message.getFieldWithDefault(msg, 3, 0),
    heartbeatDetails: (f = msg.getHeartbeatDetails()) && temporal_api_common_v1_message_pb.Payloads.toObject(includeInstance, f),
    lastHeartbeatTime: (f = msg.getLastHeartbeatTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    lastStartedTime: (f = msg.getLastStartedTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    attempt: jspb.Message.getFieldWithDefault(msg, 7, 0),
    maximumAttempts: jspb.Message.getFieldWithDefault(msg, 8, 0),
    scheduledTime: (f = msg.getScheduledTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    expirationTime: (f = msg.getExpirationTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    lastFailure: (f = msg.getLastFailure()) && temporal_api_failure_v1_message_pb.Failure.toObject(includeInstance, f),
    lastWorkerIdentity: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.workflow.v1.PendingActivityInfo}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.workflow.v1.PendingActivityInfo;
  return proto.temporal.api.workflow.v1.PendingActivityInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.workflow.v1.PendingActivityInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.workflow.v1.PendingActivityInfo}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setActivityId(value);
      break;
    case 2:
      var value = new temporal_api_common_v1_message_pb.ActivityType;
      reader.readMessage(value,temporal_api_common_v1_message_pb.ActivityType.deserializeBinaryFromReader);
      msg.setActivityType(value);
      break;
    case 3:
      var value = /** @type {!proto.temporal.api.enums.v1.PendingActivityState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 4:
      var value = new temporal_api_common_v1_message_pb.Payloads;
      reader.readMessage(value,temporal_api_common_v1_message_pb.Payloads.deserializeBinaryFromReader);
      msg.setHeartbeatDetails(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastHeartbeatTime(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastStartedTime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAttempt(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaximumAttempts(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setScheduledTime(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpirationTime(value);
      break;
    case 11:
      var value = new temporal_api_failure_v1_message_pb.Failure;
      reader.readMessage(value,temporal_api_failure_v1_message_pb.Failure.deserializeBinaryFromReader);
      msg.setLastFailure(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastWorkerIdentity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.workflow.v1.PendingActivityInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.workflow.v1.PendingActivityInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivityId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getActivityType();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      temporal_api_common_v1_message_pb.ActivityType.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getHeartbeatDetails();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      temporal_api_common_v1_message_pb.Payloads.serializeBinaryToWriter
    );
  }
  f = message.getLastHeartbeatTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLastStartedTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAttempt();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getMaximumAttempts();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getScheduledTime();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getExpirationTime();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLastFailure();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      temporal_api_failure_v1_message_pb.Failure.serializeBinaryToWriter
    );
  }
  f = message.getLastWorkerIdentity();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string activity_id = 1;
 * @return {string}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getActivityId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setActivityId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional temporal.api.common.v1.ActivityType activity_type = 2;
 * @return {?proto.temporal.api.common.v1.ActivityType}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getActivityType = function() {
  return /** @type{?proto.temporal.api.common.v1.ActivityType} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.ActivityType, 2));
};


/** @param {?proto.temporal.api.common.v1.ActivityType|undefined} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setActivityType = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.clearActivityType = function() {
  this.setActivityType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.hasActivityType = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional temporal.api.enums.v1.PendingActivityState state = 3;
 * @return {!proto.temporal.api.enums.v1.PendingActivityState}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getState = function() {
  return /** @type {!proto.temporal.api.enums.v1.PendingActivityState} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.temporal.api.enums.v1.PendingActivityState} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setState = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional temporal.api.common.v1.Payloads heartbeat_details = 4;
 * @return {?proto.temporal.api.common.v1.Payloads}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getHeartbeatDetails = function() {
  return /** @type{?proto.temporal.api.common.v1.Payloads} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.Payloads, 4));
};


/** @param {?proto.temporal.api.common.v1.Payloads|undefined} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setHeartbeatDetails = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.clearHeartbeatDetails = function() {
  this.setHeartbeatDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.hasHeartbeatDetails = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp last_heartbeat_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getLastHeartbeatTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setLastHeartbeatTime = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.clearLastHeartbeatTime = function() {
  this.setLastHeartbeatTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.hasLastHeartbeatTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp last_started_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getLastStartedTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setLastStartedTime = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.clearLastStartedTime = function() {
  this.setLastStartedTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.hasLastStartedTime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 attempt = 7;
 * @return {number}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getAttempt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setAttempt = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 maximum_attempts = 8;
 * @return {number}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getMaximumAttempts = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setMaximumAttempts = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional google.protobuf.Timestamp scheduled_time = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getScheduledTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setScheduledTime = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.clearScheduledTime = function() {
  this.setScheduledTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.hasScheduledTime = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp expiration_time = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getExpirationTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setExpirationTime = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.clearExpirationTime = function() {
  this.setExpirationTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.hasExpirationTime = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional temporal.api.failure.v1.Failure last_failure = 11;
 * @return {?proto.temporal.api.failure.v1.Failure}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getLastFailure = function() {
  return /** @type{?proto.temporal.api.failure.v1.Failure} */ (
    jspb.Message.getWrapperField(this, temporal_api_failure_v1_message_pb.Failure, 11));
};


/** @param {?proto.temporal.api.failure.v1.Failure|undefined} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setLastFailure = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.clearLastFailure = function() {
  this.setLastFailure(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.hasLastFailure = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string last_worker_identity = 12;
 * @return {string}
 */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.getLastWorkerIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.PendingActivityInfo.prototype.setLastWorkerIdentity = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.workflow.v1.PendingChildExecutionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.workflow.v1.PendingChildExecutionInfo.displayName = 'proto.temporal.api.workflow.v1.PendingChildExecutionInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.workflow.v1.PendingChildExecutionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.workflow.v1.PendingChildExecutionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    workflowId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    workflowTypeName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    initiatedId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    parentClosePolicy: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.workflow.v1.PendingChildExecutionInfo}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.workflow.v1.PendingChildExecutionInfo;
  return proto.temporal.api.workflow.v1.PendingChildExecutionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.workflow.v1.PendingChildExecutionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.workflow.v1.PendingChildExecutionInfo}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowTypeName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInitiatedId(value);
      break;
    case 5:
      var value = /** @type {!proto.temporal.api.enums.v1.ParentClosePolicy} */ (reader.readEnum());
      msg.setParentClosePolicy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.workflow.v1.PendingChildExecutionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.workflow.v1.PendingChildExecutionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWorkflowTypeName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInitiatedId();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getParentClosePolicy();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional string workflow_id = 1;
 * @return {string}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.getWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.setWorkflowId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string run_id = 2;
 * @return {string}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.getRunId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.setRunId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string workflow_type_name = 3;
 * @return {string}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.getWorkflowTypeName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.setWorkflowTypeName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 initiated_id = 4;
 * @return {number}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.getInitiatedId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.setInitiatedId = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional temporal.api.enums.v1.ParentClosePolicy parent_close_policy = 5;
 * @return {!proto.temporal.api.enums.v1.ParentClosePolicy}
 */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.getParentClosePolicy = function() {
  return /** @type {!proto.temporal.api.enums.v1.ParentClosePolicy} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.temporal.api.enums.v1.ParentClosePolicy} value */
proto.temporal.api.workflow.v1.PendingChildExecutionInfo.prototype.setParentClosePolicy = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.workflow.v1.ResetPoints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.temporal.api.workflow.v1.ResetPoints.repeatedFields_, null);
};
goog.inherits(proto.temporal.api.workflow.v1.ResetPoints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.workflow.v1.ResetPoints.displayName = 'proto.temporal.api.workflow.v1.ResetPoints';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.temporal.api.workflow.v1.ResetPoints.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.workflow.v1.ResetPoints.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.workflow.v1.ResetPoints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.workflow.v1.ResetPoints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.ResetPoints.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointsList: jspb.Message.toObjectList(msg.getPointsList(),
    proto.temporal.api.workflow.v1.ResetPointInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.workflow.v1.ResetPoints}
 */
proto.temporal.api.workflow.v1.ResetPoints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.workflow.v1.ResetPoints;
  return proto.temporal.api.workflow.v1.ResetPoints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.workflow.v1.ResetPoints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.workflow.v1.ResetPoints}
 */
proto.temporal.api.workflow.v1.ResetPoints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.temporal.api.workflow.v1.ResetPointInfo;
      reader.readMessage(value,proto.temporal.api.workflow.v1.ResetPointInfo.deserializeBinaryFromReader);
      msg.addPoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.workflow.v1.ResetPoints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.workflow.v1.ResetPoints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.workflow.v1.ResetPoints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.ResetPoints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.temporal.api.workflow.v1.ResetPointInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ResetPointInfo points = 1;
 * @return {!Array<!proto.temporal.api.workflow.v1.ResetPointInfo>}
 */
proto.temporal.api.workflow.v1.ResetPoints.prototype.getPointsList = function() {
  return /** @type{!Array<!proto.temporal.api.workflow.v1.ResetPointInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.temporal.api.workflow.v1.ResetPointInfo, 1));
};


/** @param {!Array<!proto.temporal.api.workflow.v1.ResetPointInfo>} value */
proto.temporal.api.workflow.v1.ResetPoints.prototype.setPointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.temporal.api.workflow.v1.ResetPointInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.temporal.api.workflow.v1.ResetPointInfo}
 */
proto.temporal.api.workflow.v1.ResetPoints.prototype.addPoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.temporal.api.workflow.v1.ResetPointInfo, opt_index);
};


proto.temporal.api.workflow.v1.ResetPoints.prototype.clearPointsList = function() {
  this.setPointsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.workflow.v1.ResetPointInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.workflow.v1.ResetPointInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.workflow.v1.ResetPointInfo.displayName = 'proto.temporal.api.workflow.v1.ResetPointInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.workflow.v1.ResetPointInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.workflow.v1.ResetPointInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.ResetPointInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    binaryChecksum: jspb.Message.getFieldWithDefault(msg, 1, ""),
    runId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    firstWorkflowTaskCompletedId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    expireTime: (f = msg.getExpireTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    resettable: jspb.Message.getFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.workflow.v1.ResetPointInfo}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.workflow.v1.ResetPointInfo;
  return proto.temporal.api.workflow.v1.ResetPointInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.workflow.v1.ResetPointInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.workflow.v1.ResetPointInfo}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBinaryChecksum(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFirstWorkflowTaskCompletedId(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpireTime(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setResettable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.workflow.v1.ResetPointInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.workflow.v1.ResetPointInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.workflow.v1.ResetPointInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBinaryChecksum();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRunId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFirstWorkflowTaskCompletedId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getExpireTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResettable();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional string binary_checksum = 1;
 * @return {string}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.getBinaryChecksum = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.setBinaryChecksum = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string run_id = 2;
 * @return {string}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.getRunId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.setRunId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 first_workflow_task_completed_id = 3;
 * @return {number}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.getFirstWorkflowTaskCompletedId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.setFirstWorkflowTaskCompletedId = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.setCreateTime = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.temporal.api.workflow.v1.ResetPointInfo.prototype.clearCreateTime = function() {
  this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp expire_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.getExpireTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.setExpireTime = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.temporal.api.workflow.v1.ResetPointInfo.prototype.clearExpireTime = function() {
  this.setExpireTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.hasExpireTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool resettable = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.getResettable = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.temporal.api.workflow.v1.ResetPointInfo.prototype.setResettable = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


goog.object.extend(exports, proto.temporal.api.workflow.v1);
