/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var temporal_api_common_v1_message_pb = require('../../../../temporal/api/common/v1/message_pb.js');
var temporal_api_enums_v1_workflow_pb = require('../../../../temporal/api/enums/v1/workflow_pb.js');
goog.exportSymbol('proto.temporal.api.failure.v1.ActivityFailureInfo', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.ApplicationFailureInfo', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.CanceledFailureInfo', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.Failure', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.ResetWorkflowFailureInfo', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.ServerFailureInfo', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.TerminatedFailureInfo', null, global);
goog.exportSymbol('proto.temporal.api.failure.v1.TimeoutFailureInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.ApplicationFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.ApplicationFailureInfo.displayName = 'proto.temporal.api.failure.v1.ApplicationFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.ApplicationFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.ApplicationFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nonRetryable: jspb.Message.getFieldWithDefault(msg, 2, false),
    details: (f = msg.getDetails()) && temporal_api_common_v1_message_pb.Payloads.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.ApplicationFailureInfo}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.ApplicationFailureInfo;
  return proto.temporal.api.failure.v1.ApplicationFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.ApplicationFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.ApplicationFailureInfo}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNonRetryable(value);
      break;
    case 3:
      var value = new temporal_api_common_v1_message_pb.Payloads;
      reader.readMessage(value,temporal_api_common_v1_message_pb.Payloads.deserializeBinaryFromReader);
      msg.setDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.ApplicationFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.ApplicationFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNonRetryable();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getDetails();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      temporal_api_common_v1_message_pb.Payloads.serializeBinaryToWriter
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.setType = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool non_retryable = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.getNonRetryable = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.setNonRetryable = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional temporal.api.common.v1.Payloads details = 3;
 * @return {?proto.temporal.api.common.v1.Payloads}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.getDetails = function() {
  return /** @type{?proto.temporal.api.common.v1.Payloads} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.Payloads, 3));
};


/** @param {?proto.temporal.api.common.v1.Payloads|undefined} value */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.setDetails = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.clearDetails = function() {
  this.setDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.ApplicationFailureInfo.prototype.hasDetails = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.TimeoutFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.TimeoutFailureInfo.displayName = 'proto.temporal.api.failure.v1.TimeoutFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.TimeoutFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.TimeoutFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeoutType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    lastHeartbeatDetails: (f = msg.getLastHeartbeatDetails()) && temporal_api_common_v1_message_pb.Payloads.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.TimeoutFailureInfo}
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.TimeoutFailureInfo;
  return proto.temporal.api.failure.v1.TimeoutFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.TimeoutFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.TimeoutFailureInfo}
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.temporal.api.enums.v1.TimeoutType} */ (reader.readEnum());
      msg.setTimeoutType(value);
      break;
    case 2:
      var value = new temporal_api_common_v1_message_pb.Payloads;
      reader.readMessage(value,temporal_api_common_v1_message_pb.Payloads.deserializeBinaryFromReader);
      msg.setLastHeartbeatDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.TimeoutFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.TimeoutFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeoutType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getLastHeartbeatDetails();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      temporal_api_common_v1_message_pb.Payloads.serializeBinaryToWriter
    );
  }
};


/**
 * optional temporal.api.enums.v1.TimeoutType timeout_type = 1;
 * @return {!proto.temporal.api.enums.v1.TimeoutType}
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.getTimeoutType = function() {
  return /** @type {!proto.temporal.api.enums.v1.TimeoutType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.temporal.api.enums.v1.TimeoutType} value */
proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.setTimeoutType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional temporal.api.common.v1.Payloads last_heartbeat_details = 2;
 * @return {?proto.temporal.api.common.v1.Payloads}
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.getLastHeartbeatDetails = function() {
  return /** @type{?proto.temporal.api.common.v1.Payloads} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.Payloads, 2));
};


/** @param {?proto.temporal.api.common.v1.Payloads|undefined} value */
proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.setLastHeartbeatDetails = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.clearLastHeartbeatDetails = function() {
  this.setLastHeartbeatDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.TimeoutFailureInfo.prototype.hasLastHeartbeatDetails = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.CanceledFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.CanceledFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.CanceledFailureInfo.displayName = 'proto.temporal.api.failure.v1.CanceledFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.CanceledFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.CanceledFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    details: (f = msg.getDetails()) && temporal_api_common_v1_message_pb.Payloads.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.CanceledFailureInfo}
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.CanceledFailureInfo;
  return proto.temporal.api.failure.v1.CanceledFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.CanceledFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.CanceledFailureInfo}
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new temporal_api_common_v1_message_pb.Payloads;
      reader.readMessage(value,temporal_api_common_v1_message_pb.Payloads.deserializeBinaryFromReader);
      msg.setDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.CanceledFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.CanceledFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      temporal_api_common_v1_message_pb.Payloads.serializeBinaryToWriter
    );
  }
};


/**
 * optional temporal.api.common.v1.Payloads details = 1;
 * @return {?proto.temporal.api.common.v1.Payloads}
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.prototype.getDetails = function() {
  return /** @type{?proto.temporal.api.common.v1.Payloads} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.Payloads, 1));
};


/** @param {?proto.temporal.api.common.v1.Payloads|undefined} value */
proto.temporal.api.failure.v1.CanceledFailureInfo.prototype.setDetails = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.temporal.api.failure.v1.CanceledFailureInfo.prototype.clearDetails = function() {
  this.setDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.CanceledFailureInfo.prototype.hasDetails = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.TerminatedFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.TerminatedFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.TerminatedFailureInfo.displayName = 'proto.temporal.api.failure.v1.TerminatedFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.TerminatedFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.TerminatedFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.TerminatedFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.TerminatedFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.TerminatedFailureInfo}
 */
proto.temporal.api.failure.v1.TerminatedFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.TerminatedFailureInfo;
  return proto.temporal.api.failure.v1.TerminatedFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.TerminatedFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.TerminatedFailureInfo}
 */
proto.temporal.api.failure.v1.TerminatedFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.TerminatedFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.TerminatedFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.TerminatedFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.TerminatedFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.ServerFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.ServerFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.ServerFailureInfo.displayName = 'proto.temporal.api.failure.v1.ServerFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.ServerFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.ServerFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.ServerFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ServerFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    nonRetryable: jspb.Message.getFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.ServerFailureInfo}
 */
proto.temporal.api.failure.v1.ServerFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.ServerFailureInfo;
  return proto.temporal.api.failure.v1.ServerFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.ServerFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.ServerFailureInfo}
 */
proto.temporal.api.failure.v1.ServerFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNonRetryable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.ServerFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.ServerFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.ServerFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ServerFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNonRetryable();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool non_retryable = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.temporal.api.failure.v1.ServerFailureInfo.prototype.getNonRetryable = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.temporal.api.failure.v1.ServerFailureInfo.prototype.setNonRetryable = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.ResetWorkflowFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.displayName = 'proto.temporal.api.failure.v1.ResetWorkflowFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.ResetWorkflowFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    lastHeartbeatDetails: (f = msg.getLastHeartbeatDetails()) && temporal_api_common_v1_message_pb.Payloads.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.ResetWorkflowFailureInfo}
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.ResetWorkflowFailureInfo;
  return proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.ResetWorkflowFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.ResetWorkflowFailureInfo}
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new temporal_api_common_v1_message_pb.Payloads;
      reader.readMessage(value,temporal_api_common_v1_message_pb.Payloads.deserializeBinaryFromReader);
      msg.setLastHeartbeatDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.ResetWorkflowFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLastHeartbeatDetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      temporal_api_common_v1_message_pb.Payloads.serializeBinaryToWriter
    );
  }
};


/**
 * optional temporal.api.common.v1.Payloads last_heartbeat_details = 1;
 * @return {?proto.temporal.api.common.v1.Payloads}
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.prototype.getLastHeartbeatDetails = function() {
  return /** @type{?proto.temporal.api.common.v1.Payloads} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.Payloads, 1));
};


/** @param {?proto.temporal.api.common.v1.Payloads|undefined} value */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.prototype.setLastHeartbeatDetails = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.prototype.clearLastHeartbeatDetails = function() {
  this.setLastHeartbeatDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.prototype.hasLastHeartbeatDetails = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.ActivityFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.ActivityFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.ActivityFailureInfo.displayName = 'proto.temporal.api.failure.v1.ActivityFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.ActivityFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.ActivityFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    scheduledEventId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    startedEventId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    identity: jspb.Message.getFieldWithDefault(msg, 3, ""),
    activityType: (f = msg.getActivityType()) && temporal_api_common_v1_message_pb.ActivityType.toObject(includeInstance, f),
    activityId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    retryState: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.ActivityFailureInfo}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.ActivityFailureInfo;
  return proto.temporal.api.failure.v1.ActivityFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.ActivityFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.ActivityFailureInfo}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setScheduledEventId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartedEventId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentity(value);
      break;
    case 4:
      var value = new temporal_api_common_v1_message_pb.ActivityType;
      reader.readMessage(value,temporal_api_common_v1_message_pb.ActivityType.deserializeBinaryFromReader);
      msg.setActivityType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setActivityId(value);
      break;
    case 6:
      var value = /** @type {!proto.temporal.api.enums.v1.RetryState} */ (reader.readEnum());
      msg.setRetryState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.ActivityFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.ActivityFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScheduledEventId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getStartedEventId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getIdentity();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getActivityType();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      temporal_api_common_v1_message_pb.ActivityType.serializeBinaryToWriter
    );
  }
  f = message.getActivityId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRetryState();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional int64 scheduled_event_id = 1;
 * @return {number}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.getScheduledEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.setScheduledEventId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 started_event_id = 2;
 * @return {number}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.getStartedEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.setStartedEventId = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string identity = 3;
 * @return {string}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.getIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.setIdentity = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional temporal.api.common.v1.ActivityType activity_type = 4;
 * @return {?proto.temporal.api.common.v1.ActivityType}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.getActivityType = function() {
  return /** @type{?proto.temporal.api.common.v1.ActivityType} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.ActivityType, 4));
};


/** @param {?proto.temporal.api.common.v1.ActivityType|undefined} value */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.setActivityType = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.clearActivityType = function() {
  this.setActivityType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.hasActivityType = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string activity_id = 5;
 * @return {string}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.getActivityId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.setActivityId = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional temporal.api.enums.v1.RetryState retry_state = 6;
 * @return {!proto.temporal.api.enums.v1.RetryState}
 */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.getRetryState = function() {
  return /** @type {!proto.temporal.api.enums.v1.RetryState} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.temporal.api.enums.v1.RetryState} value */
proto.temporal.api.failure.v1.ActivityFailureInfo.prototype.setRetryState = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.displayName = 'proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    namespace: jspb.Message.getFieldWithDefault(msg, 1, ""),
    workflowExecution: (f = msg.getWorkflowExecution()) && temporal_api_common_v1_message_pb.WorkflowExecution.toObject(includeInstance, f),
    workflowType: (f = msg.getWorkflowType()) && temporal_api_common_v1_message_pb.WorkflowType.toObject(includeInstance, f),
    initiatedEventId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    startedEventId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    retryState: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo;
  return proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 2:
      var value = new temporal_api_common_v1_message_pb.WorkflowExecution;
      reader.readMessage(value,temporal_api_common_v1_message_pb.WorkflowExecution.deserializeBinaryFromReader);
      msg.setWorkflowExecution(value);
      break;
    case 3:
      var value = new temporal_api_common_v1_message_pb.WorkflowType;
      reader.readMessage(value,temporal_api_common_v1_message_pb.WorkflowType.deserializeBinaryFromReader);
      msg.setWorkflowType(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInitiatedEventId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartedEventId(value);
      break;
    case 6:
      var value = /** @type {!proto.temporal.api.enums.v1.RetryState} */ (reader.readEnum());
      msg.setRetryState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWorkflowExecution();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      temporal_api_common_v1_message_pb.WorkflowExecution.serializeBinaryToWriter
    );
  }
  f = message.getWorkflowType();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      temporal_api_common_v1_message_pb.WorkflowType.serializeBinaryToWriter
    );
  }
  f = message.getInitiatedEventId();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getStartedEventId();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getRetryState();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional string namespace = 1;
 * @return {string}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.setNamespace = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional temporal.api.common.v1.WorkflowExecution workflow_execution = 2;
 * @return {?proto.temporal.api.common.v1.WorkflowExecution}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.getWorkflowExecution = function() {
  return /** @type{?proto.temporal.api.common.v1.WorkflowExecution} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.WorkflowExecution, 2));
};


/** @param {?proto.temporal.api.common.v1.WorkflowExecution|undefined} value */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.setWorkflowExecution = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.clearWorkflowExecution = function() {
  this.setWorkflowExecution(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.hasWorkflowExecution = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional temporal.api.common.v1.WorkflowType workflow_type = 3;
 * @return {?proto.temporal.api.common.v1.WorkflowType}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.getWorkflowType = function() {
  return /** @type{?proto.temporal.api.common.v1.WorkflowType} */ (
    jspb.Message.getWrapperField(this, temporal_api_common_v1_message_pb.WorkflowType, 3));
};


/** @param {?proto.temporal.api.common.v1.WorkflowType|undefined} value */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.setWorkflowType = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.clearWorkflowType = function() {
  this.setWorkflowType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.hasWorkflowType = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 initiated_event_id = 4;
 * @return {number}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.getInitiatedEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.setInitiatedEventId = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 started_event_id = 5;
 * @return {number}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.getStartedEventId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.setStartedEventId = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional temporal.api.enums.v1.RetryState retry_state = 6;
 * @return {!proto.temporal.api.enums.v1.RetryState}
 */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.getRetryState = function() {
  return /** @type {!proto.temporal.api.enums.v1.RetryState} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.temporal.api.enums.v1.RetryState} value */
proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.prototype.setRetryState = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.failure.v1.Failure = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.temporal.api.failure.v1.Failure.oneofGroups_);
};
goog.inherits(proto.temporal.api.failure.v1.Failure, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.failure.v1.Failure.displayName = 'proto.temporal.api.failure.v1.Failure';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.temporal.api.failure.v1.Failure.oneofGroups_ = [[5,6,7,8,9,10,11,12]];

/**
 * @enum {number}
 */
proto.temporal.api.failure.v1.Failure.FailureInfoCase = {
  FAILURE_INFO_NOT_SET: 0,
  APPLICATION_FAILURE_INFO: 5,
  TIMEOUT_FAILURE_INFO: 6,
  CANCELED_FAILURE_INFO: 7,
  TERMINATED_FAILURE_INFO: 8,
  SERVER_FAILURE_INFO: 9,
  RESET_WORKFLOW_FAILURE_INFO: 10,
  ACTIVITY_FAILURE_INFO: 11,
  CHILD_WORKFLOW_EXECUTION_FAILURE_INFO: 12
};

/**
 * @return {proto.temporal.api.failure.v1.Failure.FailureInfoCase}
 */
proto.temporal.api.failure.v1.Failure.prototype.getFailureInfoCase = function() {
  return /** @type {proto.temporal.api.failure.v1.Failure.FailureInfoCase} */(jspb.Message.computeOneofCase(this, proto.temporal.api.failure.v1.Failure.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.failure.v1.Failure.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.failure.v1.Failure.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.failure.v1.Failure} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.Failure.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    source: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stackTrace: jspb.Message.getFieldWithDefault(msg, 3, ""),
    cause: (f = msg.getCause()) && proto.temporal.api.failure.v1.Failure.toObject(includeInstance, f),
    applicationFailureInfo: (f = msg.getApplicationFailureInfo()) && proto.temporal.api.failure.v1.ApplicationFailureInfo.toObject(includeInstance, f),
    timeoutFailureInfo: (f = msg.getTimeoutFailureInfo()) && proto.temporal.api.failure.v1.TimeoutFailureInfo.toObject(includeInstance, f),
    canceledFailureInfo: (f = msg.getCanceledFailureInfo()) && proto.temporal.api.failure.v1.CanceledFailureInfo.toObject(includeInstance, f),
    terminatedFailureInfo: (f = msg.getTerminatedFailureInfo()) && proto.temporal.api.failure.v1.TerminatedFailureInfo.toObject(includeInstance, f),
    serverFailureInfo: (f = msg.getServerFailureInfo()) && proto.temporal.api.failure.v1.ServerFailureInfo.toObject(includeInstance, f),
    resetWorkflowFailureInfo: (f = msg.getResetWorkflowFailureInfo()) && proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.toObject(includeInstance, f),
    activityFailureInfo: (f = msg.getActivityFailureInfo()) && proto.temporal.api.failure.v1.ActivityFailureInfo.toObject(includeInstance, f),
    childWorkflowExecutionFailureInfo: (f = msg.getChildWorkflowExecutionFailureInfo()) && proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.failure.v1.Failure}
 */
proto.temporal.api.failure.v1.Failure.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.failure.v1.Failure;
  return proto.temporal.api.failure.v1.Failure.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.failure.v1.Failure} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.failure.v1.Failure}
 */
proto.temporal.api.failure.v1.Failure.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStackTrace(value);
      break;
    case 4:
      var value = new proto.temporal.api.failure.v1.Failure;
      reader.readMessage(value,proto.temporal.api.failure.v1.Failure.deserializeBinaryFromReader);
      msg.setCause(value);
      break;
    case 5:
      var value = new proto.temporal.api.failure.v1.ApplicationFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.ApplicationFailureInfo.deserializeBinaryFromReader);
      msg.setApplicationFailureInfo(value);
      break;
    case 6:
      var value = new proto.temporal.api.failure.v1.TimeoutFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.TimeoutFailureInfo.deserializeBinaryFromReader);
      msg.setTimeoutFailureInfo(value);
      break;
    case 7:
      var value = new proto.temporal.api.failure.v1.CanceledFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.CanceledFailureInfo.deserializeBinaryFromReader);
      msg.setCanceledFailureInfo(value);
      break;
    case 8:
      var value = new proto.temporal.api.failure.v1.TerminatedFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.TerminatedFailureInfo.deserializeBinaryFromReader);
      msg.setTerminatedFailureInfo(value);
      break;
    case 9:
      var value = new proto.temporal.api.failure.v1.ServerFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.ServerFailureInfo.deserializeBinaryFromReader);
      msg.setServerFailureInfo(value);
      break;
    case 10:
      var value = new proto.temporal.api.failure.v1.ResetWorkflowFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.deserializeBinaryFromReader);
      msg.setResetWorkflowFailureInfo(value);
      break;
    case 11:
      var value = new proto.temporal.api.failure.v1.ActivityFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.ActivityFailureInfo.deserializeBinaryFromReader);
      msg.setActivityFailureInfo(value);
      break;
    case 12:
      var value = new proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo;
      reader.readMessage(value,proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.deserializeBinaryFromReader);
      msg.setChildWorkflowExecutionFailureInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.failure.v1.Failure.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.failure.v1.Failure.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.failure.v1.Failure} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.failure.v1.Failure.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStackTrace();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCause();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.temporal.api.failure.v1.Failure.serializeBinaryToWriter
    );
  }
  f = message.getApplicationFailureInfo();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.temporal.api.failure.v1.ApplicationFailureInfo.serializeBinaryToWriter
    );
  }
  f = message.getTimeoutFailureInfo();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.temporal.api.failure.v1.TimeoutFailureInfo.serializeBinaryToWriter
    );
  }
  f = message.getCanceledFailureInfo();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.temporal.api.failure.v1.CanceledFailureInfo.serializeBinaryToWriter
    );
  }
  f = message.getTerminatedFailureInfo();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.temporal.api.failure.v1.TerminatedFailureInfo.serializeBinaryToWriter
    );
  }
  f = message.getServerFailureInfo();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.temporal.api.failure.v1.ServerFailureInfo.serializeBinaryToWriter
    );
  }
  f = message.getResetWorkflowFailureInfo();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.temporal.api.failure.v1.ResetWorkflowFailureInfo.serializeBinaryToWriter
    );
  }
  f = message.getActivityFailureInfo();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.temporal.api.failure.v1.ActivityFailureInfo.serializeBinaryToWriter
    );
  }
  f = message.getChildWorkflowExecutionFailureInfo();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.temporal.api.failure.v1.Failure.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.failure.v1.Failure.prototype.setMessage = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string source = 2;
 * @return {string}
 */
proto.temporal.api.failure.v1.Failure.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.temporal.api.failure.v1.Failure.prototype.setSource = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string stack_trace = 3;
 * @return {string}
 */
proto.temporal.api.failure.v1.Failure.prototype.getStackTrace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.temporal.api.failure.v1.Failure.prototype.setStackTrace = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Failure cause = 4;
 * @return {?proto.temporal.api.failure.v1.Failure}
 */
proto.temporal.api.failure.v1.Failure.prototype.getCause = function() {
  return /** @type{?proto.temporal.api.failure.v1.Failure} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.Failure, 4));
};


/** @param {?proto.temporal.api.failure.v1.Failure|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setCause = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearCause = function() {
  this.setCause(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasCause = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ApplicationFailureInfo application_failure_info = 5;
 * @return {?proto.temporal.api.failure.v1.ApplicationFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getApplicationFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.ApplicationFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.ApplicationFailureInfo, 5));
};


/** @param {?proto.temporal.api.failure.v1.ApplicationFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setApplicationFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearApplicationFailureInfo = function() {
  this.setApplicationFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasApplicationFailureInfo = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional TimeoutFailureInfo timeout_failure_info = 6;
 * @return {?proto.temporal.api.failure.v1.TimeoutFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getTimeoutFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.TimeoutFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.TimeoutFailureInfo, 6));
};


/** @param {?proto.temporal.api.failure.v1.TimeoutFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setTimeoutFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearTimeoutFailureInfo = function() {
  this.setTimeoutFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasTimeoutFailureInfo = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional CanceledFailureInfo canceled_failure_info = 7;
 * @return {?proto.temporal.api.failure.v1.CanceledFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getCanceledFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.CanceledFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.CanceledFailureInfo, 7));
};


/** @param {?proto.temporal.api.failure.v1.CanceledFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setCanceledFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearCanceledFailureInfo = function() {
  this.setCanceledFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasCanceledFailureInfo = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional TerminatedFailureInfo terminated_failure_info = 8;
 * @return {?proto.temporal.api.failure.v1.TerminatedFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getTerminatedFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.TerminatedFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.TerminatedFailureInfo, 8));
};


/** @param {?proto.temporal.api.failure.v1.TerminatedFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setTerminatedFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearTerminatedFailureInfo = function() {
  this.setTerminatedFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasTerminatedFailureInfo = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional ServerFailureInfo server_failure_info = 9;
 * @return {?proto.temporal.api.failure.v1.ServerFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getServerFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.ServerFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.ServerFailureInfo, 9));
};


/** @param {?proto.temporal.api.failure.v1.ServerFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setServerFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearServerFailureInfo = function() {
  this.setServerFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasServerFailureInfo = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ResetWorkflowFailureInfo reset_workflow_failure_info = 10;
 * @return {?proto.temporal.api.failure.v1.ResetWorkflowFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getResetWorkflowFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.ResetWorkflowFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.ResetWorkflowFailureInfo, 10));
};


/** @param {?proto.temporal.api.failure.v1.ResetWorkflowFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setResetWorkflowFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearResetWorkflowFailureInfo = function() {
  this.setResetWorkflowFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasResetWorkflowFailureInfo = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional ActivityFailureInfo activity_failure_info = 11;
 * @return {?proto.temporal.api.failure.v1.ActivityFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getActivityFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.ActivityFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.ActivityFailureInfo, 11));
};


/** @param {?proto.temporal.api.failure.v1.ActivityFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setActivityFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearActivityFailureInfo = function() {
  this.setActivityFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasActivityFailureInfo = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ChildWorkflowExecutionFailureInfo child_workflow_execution_failure_info = 12;
 * @return {?proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo}
 */
proto.temporal.api.failure.v1.Failure.prototype.getChildWorkflowExecutionFailureInfo = function() {
  return /** @type{?proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo} */ (
    jspb.Message.getWrapperField(this, proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo, 12));
};


/** @param {?proto.temporal.api.failure.v1.ChildWorkflowExecutionFailureInfo|undefined} value */
proto.temporal.api.failure.v1.Failure.prototype.setChildWorkflowExecutionFailureInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.temporal.api.failure.v1.Failure.oneofGroups_[0], value);
};


proto.temporal.api.failure.v1.Failure.prototype.clearChildWorkflowExecutionFailureInfo = function() {
  this.setChildWorkflowExecutionFailureInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.temporal.api.failure.v1.Failure.prototype.hasChildWorkflowExecutionFailureInfo = function() {
  return jspb.Message.getField(this, 12) != null;
};


goog.object.extend(exports, proto.temporal.api.failure.v1);
