/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.temporal.api.enums.v1.EventType', null, global);
/**
 * @enum {number}
 */
proto.temporal.api.enums.v1.EventType = {
  EVENT_TYPE_UNSPECIFIED: 0,
  EVENT_TYPE_WORKFLOW_EXECUTION_STARTED: 1,
  EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED: 2,
  EVENT_TYPE_WORKFLOW_EXECUTION_FAILED: 3,
  EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT: 4,
  EVENT_TYPE_WORKFLOW_TASK_SCHEDULED: 5,
  EVENT_TYPE_WORKFLOW_TASK_STARTED: 6,
  EVENT_TYPE_WORKFLOW_TASK_COMPLETED: 7,
  EVENT_TYPE_WORKFLOW_TASK_TIMED_OUT: 8,
  EVENT_TYPE_WORKFLOW_TASK_FAILED: 9,
  EVENT_TYPE_ACTIVITY_TASK_SCHEDULED: 10,
  EVENT_TYPE_ACTIVITY_TASK_STARTED: 11,
  EVENT_TYPE_ACTIVITY_TASK_COMPLETED: 12,
  EVENT_TYPE_ACTIVITY_TASK_FAILED: 13,
  EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT: 14,
  EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED: 15,
  EVENT_TYPE_ACTIVITY_TASK_CANCELED: 16,
  EVENT_TYPE_TIMER_STARTED: 17,
  EVENT_TYPE_TIMER_FIRED: 18,
  EVENT_TYPE_TIMER_CANCELED: 19,
  EVENT_TYPE_WORKFLOW_EXECUTION_CANCEL_REQUESTED: 20,
  EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED: 21,
  EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED: 22,
  EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED: 23,
  EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_CANCEL_REQUESTED: 24,
  EVENT_TYPE_MARKER_RECORDED: 25,
  EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED: 26,
  EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED: 27,
  EVENT_TYPE_WORKFLOW_EXECUTION_CONTINUED_AS_NEW: 28,
  EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED: 29,
  EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_FAILED: 30,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_STARTED: 31,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_COMPLETED: 32,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_FAILED: 33,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_CANCELED: 34,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TIMED_OUT: 35,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TERMINATED: 36,
  EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED: 37,
  EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED: 38,
  EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_SIGNALED: 39,
  EVENT_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES: 40
};

goog.object.extend(exports, proto.temporal.api.enums.v1);
