/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.temporal.api.replication.v1.ClusterReplicationConfig', null, global);
goog.exportSymbol('proto.temporal.api.replication.v1.NamespaceReplicationConfig', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temporal.api.replication.v1.ClusterReplicationConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.replication.v1.ClusterReplicationConfig.displayName = 'proto.temporal.api.replication.v1.ClusterReplicationConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.replication.v1.ClusterReplicationConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.replication.v1.ClusterReplicationConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    clusterName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.replication.v1.ClusterReplicationConfig}
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.replication.v1.ClusterReplicationConfig;
  return proto.temporal.api.replication.v1.ClusterReplicationConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.replication.v1.ClusterReplicationConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.replication.v1.ClusterReplicationConfig}
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClusterName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.replication.v1.ClusterReplicationConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.replication.v1.ClusterReplicationConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClusterName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string cluster_name = 1;
 * @return {string}
 */
proto.temporal.api.replication.v1.ClusterReplicationConfig.prototype.getClusterName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.replication.v1.ClusterReplicationConfig.prototype.setClusterName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.temporal.api.replication.v1.NamespaceReplicationConfig.repeatedFields_, null);
};
goog.inherits(proto.temporal.api.replication.v1.NamespaceReplicationConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.temporal.api.replication.v1.NamespaceReplicationConfig.displayName = 'proto.temporal.api.replication.v1.NamespaceReplicationConfig';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.temporal.api.replication.v1.NamespaceReplicationConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temporal.api.replication.v1.NamespaceReplicationConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    activeClusterName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    clustersList: jspb.Message.toObjectList(msg.getClustersList(),
    proto.temporal.api.replication.v1.ClusterReplicationConfig.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temporal.api.replication.v1.NamespaceReplicationConfig}
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temporal.api.replication.v1.NamespaceReplicationConfig;
  return proto.temporal.api.replication.v1.NamespaceReplicationConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temporal.api.replication.v1.NamespaceReplicationConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temporal.api.replication.v1.NamespaceReplicationConfig}
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setActiveClusterName(value);
      break;
    case 2:
      var value = new proto.temporal.api.replication.v1.ClusterReplicationConfig;
      reader.readMessage(value,proto.temporal.api.replication.v1.ClusterReplicationConfig.deserializeBinaryFromReader);
      msg.addClusters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temporal.api.replication.v1.NamespaceReplicationConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temporal.api.replication.v1.NamespaceReplicationConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActiveClusterName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClustersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.temporal.api.replication.v1.ClusterReplicationConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional string active_cluster_name = 1;
 * @return {string}
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.getActiveClusterName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.setActiveClusterName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated ClusterReplicationConfig clusters = 2;
 * @return {!Array<!proto.temporal.api.replication.v1.ClusterReplicationConfig>}
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.getClustersList = function() {
  return /** @type{!Array<!proto.temporal.api.replication.v1.ClusterReplicationConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.temporal.api.replication.v1.ClusterReplicationConfig, 2));
};


/** @param {!Array<!proto.temporal.api.replication.v1.ClusterReplicationConfig>} value */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.setClustersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.temporal.api.replication.v1.ClusterReplicationConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.temporal.api.replication.v1.ClusterReplicationConfig}
 */
proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.addClusters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.temporal.api.replication.v1.ClusterReplicationConfig, opt_index);
};


proto.temporal.api.replication.v1.NamespaceReplicationConfig.prototype.clearClustersList = function() {
  this.setClustersList([]);
};


goog.object.extend(exports, proto.temporal.api.replication.v1);
